# This file was generated by GoReleaser. DO NOT EDIT.
cask "confluence-mcp" do
  version "0.0.13"

  on_macos do
    on_arm do
      sha256 "bedb1c6a15d73ac3027737ee0eafa1ef81421d09f14725eac8f1d0c1ec3499d3"
      url "https://github.com/sishbi/confluence-mcp/releases/download/v#{version}/confluence-mcp_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "48fb15e4564a81b9a7e10d1072a82b7b2ed4f1d235d23637ea1f64497c4c4a0c"
      url "https://github.com/sishbi/confluence-mcp/releases/download/v#{version}/confluence-mcp_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "875c92d1949891ed1573d8b30a509ab957d494d2d65c242eae895e79a8a4c734"
      url "https://github.com/sishbi/confluence-mcp/releases/download/v#{version}/confluence-mcp_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "51e23e713185c9e26cac6f6d85df8cd6d5283dd28ca26d1c54acced7bd3bfc4e"
      url "https://github.com/sishbi/confluence-mcp/releases/download/v#{version}/confluence-mcp_linux_amd64.tar.gz"
    end
  end

  name "confluence-mcp"
  desc "Confluence MCP server — give your AI assistant full Confluence access"
  homepage "https://github.com/sishbi/confluence-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "confluence-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/confluence-mcp"]
    end
  end

  # No zap stanza required
end
