# This file was generated by GoReleaser. DO NOT EDIT.
cask "confluence-mcp" do
  version "0.0.12"

  on_macos do
    on_intel do
      sha256 "c56af74caa55e1d5e2c553562e826c577fb19f8a40aa879cfab9bdf17ae4a7ff"
      url "https://github.com/sishbi/confluence-mcp/releases/download/v#{version}/confluence-mcp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d5a1ea7e037c65b1b68a2bf0c700096f462465c29f9530d1f894c4374fe3747b"
      url "https://github.com/sishbi/confluence-mcp/releases/download/v#{version}/confluence-mcp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4443139455f3dcad108a7b8f31f041b3aa100f9d6e734af99b463e78a19b01c5"
      url "https://github.com/sishbi/confluence-mcp/releases/download/v#{version}/confluence-mcp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f99660ab52df404788a3085f2a70f3087594f3d78053b71d714a516b99715d87"
      url "https://github.com/sishbi/confluence-mcp/releases/download/v#{version}/confluence-mcp_linux_arm64.tar.gz"
    end
  end

  name "confluence-mcp"
  desc "Confluence MCP server — give your AI assistant full Confluence access"
  homepage "https://github.com/sishbi/confluence-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "confluence-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/confluence-mcp"]
    end
  end

  # No zap stanza required

end
