# This file was generated by GoReleaser. DO NOT EDIT.
cask "confluence-mcp" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "confluence-mcp"], chdir: "."
  end if OS.mac?

  version "0.0.15"

  on_macos do
    on_arm do
      sha256 "038996db7ed4d85de2b23d31c4084d567e8069f753338f0d0dabf04d921f70f9"
      url "https://github.com/sishbi/confluence-mcp/releases/download/v#{version}/confluence-mcp_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4b746c47027452a711f8d75b1232fefea545601f6437338c71f60c5cd043e12b"
      url "https://github.com/sishbi/confluence-mcp/releases/download/v#{version}/confluence-mcp_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "eda1e78520c465a6891205439ce729face44f961c073e508538e740ea8d04cd7"
      url "https://github.com/sishbi/confluence-mcp/releases/download/v#{version}/confluence-mcp_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a0eee96d28b5a96a6b90dbd776f8f50e7f40b992a04712fbf5122023e0300a0f"
      url "https://github.com/sishbi/confluence-mcp/releases/download/v#{version}/confluence-mcp_linux_amd64.tar.gz"
    end
  end

  name "confluence-mcp"
  desc "Confluence MCP server — give your AI assistant full Confluence access"
  homepage "https://github.com/sishbi/confluence-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "confluence-mcp"

  # No zap stanza required
end
