# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira-mcp" do
  name "jira-mcp"
  desc "JIRA MCP server — give your AI assistant full JIRA access"
  homepage "https://github.com/mmatczuk/jira-mcp"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jira-mcp"

  on_macos do
    on_intel do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_amd64.tar.gz"
      sha256 "67f9237ee101bfb006f7e99820732e9cf865f23bc7b58f8511c18382edf2204c"
    end
    on_arm do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_arm64.tar.gz"
      sha256 "5b6ebacc754a17f5833694d25acf32f643211e575c0c1a5fb72b3a4f27971fbe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_amd64.tar.gz"
      sha256 "20b7805a3e624fb925e254c1d2f3d719929c7b83e02d7286dd09d7e714596fc9"
    end
    on_arm do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_arm64.tar.gz"
      sha256 "0e3f1a164b5ccb7f0eebf03d5cc4769e5f838ed1bf324bdef17cebe9ede2711b"
    end
  end

  # No zap stanza required
end
