# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira-mcp" do
  name "jira-mcp"
  desc "JIRA MCP server — give your AI assistant full JIRA access"
  homepage "https://github.com/mmatczuk/jira-mcp"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jira-mcp"

  on_macos do
    on_intel do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_amd64.tar.gz"
      sha256 "9371bdf9c0edf0a41b8a1ced99b2a70c2b507bfa7f174680c06981c09da48c72"
    end
    on_arm do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_arm64.tar.gz"
      sha256 "6d28569be7edb222de787861230029b5d09729405e4369fb01ecb48475a5d0e0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_amd64.tar.gz"
      sha256 "104d1c6e990879fd27c2518ab5e00798e6d63b29f85b2cde6fab32cb73844b5e"
    end
    on_arm do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_arm64.tar.gz"
      sha256 "031b97c541348f2645f572dc02fd1bcbd255bc93d87e4ffb972dd5dbb479543a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jira-mcp"]
    end
  end

  # No zap stanza required
end
