# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira-mcp" do
  disable :quarantine

  name "jira-mcp"
  desc "JIRA MCP server — give your AI assistant full JIRA access"
  homepage "https://github.com/mmatczuk/jira-mcp"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jira-mcp"

  on_macos do
    on_intel do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_amd64.tar.gz"
      sha256 "fb3e2dd5132d57fab0c9615eef5542b5540d238655597c746eacd52322da09c8"
    end
    on_arm do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_arm64.tar.gz"
      sha256 "ef10d88ed7ff4d50a24288453f87cfecd1c673149beaa74d13160419f04410e8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_amd64.tar.gz"
      sha256 "153aab54e6c8eef77b794190a3b699cb467c3a749c6c2dbb9bcea6f7cf2ca8c1"
    end
    on_arm do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_arm64.tar.gz"
      sha256 "41b19d2fca084874119a77762912fcc4b5add933b902c2da1bcd1bfdfef5cd5c"
    end
  end

  # No zap stanza required
end
